### ISSUE TITLE
Support for LCD-OLinuXino 4.3" and 7" panels on sun7i-a20

### ISSUE THREAD

**Issue by MerlijnWajer** [OLIMEX/OLIMEX-sunxi-overlays#3]
Would it be possible to get overlays for this (Support for LCD-OLinuXino 4.3" and 7" panels on sun7i-a20) configuration?

I've been struggling for a while now trying to get this to work on Linux 5.11, and I cannot figure out what device tree modifications I need to make exactly.

**Comment by stefansaraev** [comment]
please, look at https://github.com/OLIMEX/olinuxino-overlays

**Comment by MerlijnWajer** [comment]
Thank you!
